/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_mylibs_WRAP_H_
#define SWIG_mylibs_WRAP_H_

class SwigDirector_MyIf : public MyIf, public Swig::Director {

public:
    SwigDirector_MyIf();
    virtual void myfunc(Student arg0);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackmyfunc);

private:
    SWIG_Callback0_t swig_callbackmyfunc;
    void swig_init_callbacks();
};


#endif
