OPT = -Wall -O3

main: 1_row-and-column-major-traversal.out

1_row-and-column-major-traversal.out:	1_row-and-column-major-traversal.c
	gcc -o 1_row-and-column-major-traversal.out 1_row-and-column-major-traversal.c $(OPT)