main: base-constructor.out copy-constructor.out

base-constructor.out: base-constructor.cpp
	g++ base-constructor.cpp -o base-constructor.out
copy-constructor.out: copy-constructor.cpp
	g++ copy-constructor.cpp -o copy-constructor.out